import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import AlarmsDrawer from "@/components/alarms-drawer";
import { AuthProvider } from "./context/authContext";
import AuthenticatedLayout from "@/components/authenticated-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DataMiner | Smart Park Ops",
  description: "Generated by Skyline Lambda Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthenticatedLayout>
            <SidebarProvider>
              <AppSidebar />
              {children}
              <AlarmsDrawer />
            </SidebarProvider>
          </AuthenticatedLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
